// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCU0IPsZJVfSTqGUHgsNFB-Q77V6P2wRs',
    appId: '1:52236399052:web:446125ab8f284a274cad69',
    messagingSenderId: '52236399052',
    projectId: 'virtual-chat-01',
    authDomain: 'virtual-chat-01.firebaseapp.com',
    storageBucket: 'virtual-chat-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISww6lOSsYEx0NqbH8nEgGjWfGQWZbY4',
    appId: '1:52236399052:android:c3bc8d8f85fceb294cad69',
    messagingSenderId: '52236399052',
    projectId: 'virtual-chat-01',
    storageBucket: 'virtual-chat-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpdNJYDkt9wkqOjjT89CxQyCJFHcCJKo',
    appId: '1:52236399052:ios:4bf5bcd110c1c1a84cad69',
    messagingSenderId: '52236399052',
    projectId: 'virtual-chat-01',
    storageBucket: 'virtual-chat-01.appspot.com',
    iosBundleId: 'com.example.virtual',
  );
}
